using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ServiceHealthReader.Data.Models
{
    /// <summary>
    /// Used for parsing the response from the API
    /// </summary>
    public class DiagnosticResponse
    {
        public Serverinfo ServerInfo { get; set; }
    }

    /// <summary>
    /// An actual entity used for storing stuff
    /// </summary>
    public class Serverinfo
    {
        public string DataCenter { get; set; }
        public string Slice { get; set; }
        public string Ring { get; set; }
        public string ScaleUnit { get; set; }
        public string RoleInstance { get; set; }

        /// <summary>
        /// This is internally used, autogenerated ID. Not meaningful in any way.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int? ServerInfoId { get; set; } = null;

        /// <summary>
        /// Foreign Key for Tenant
        /// </summary>
        public Tenant Tenant { get; set; }
    }
}